version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    external: true



# PS D:\GITRepos\Docker\YEAR2024\TRAINING2023-Jan11-00> docker-compose -f docker-compose-mongo.yml up
# PS D:\GITRepos\Docker\YEAR2024\TRAINING2023-Jan11-00> docker-compose -f .\docker-compose-mongo.yml ps
# PS D:\GITRepos\Docker\YEAR2024\TRAINING2023-Jan11-00> docker-compose -f docker-compose-mongo.yml down